<?php
// Automatically Generated by TestLink Installer - Fri, 02 May 14 14:49:30 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', getenv('OPENSHIFT_MYSQL_DB_USERNAME'));
define('DB_PASS', getenv('OPENSHIFT_MYSQL_DB_PASSWORD'));
define('DB_HOST', getenv('OPENSHIFT_MYSQL_DB_HOST') . ':' . getenv('OPENSHIFT_MYSQL_DB_PORT'));
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
